// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           36
// Async Callback:                       1
// Total number of exported functions:  38

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    elven_nft_minter
    (
        issueToken
        setLocalRoles
        pauseMinting
        startMinting
        setDrop
        unsetDrop
        setNewPrice
        changeBaseCids
        setNewTokensLimitPerAddress
        giveaway
        claimScFunds
        enableAllowlist
        disableAllowlist
        populateAllowlist
        clearAllowlist
        removeAllowlistAddress
        mint
        shuffle
        getDropTokensLeft
        getTotalTokensLeft
        getMintedPerAddressPerDrop
        getAllowlistAddressCheck
        getAllowlistSize
        getNftTokenId
        getCollectionTokenName
        getNftTokenName
        getNftPrice
        getProvenanceHash
        getTokensLimitPerAddressTotal
        getMintedPerAddressTotal
        getTokensLimitPerAddressPerDrop
        isAllowlistEnabled
        isDropActive
        getTotalSupply
        isMintingPaused
        getTotalSupplyOfCurrentDrop
        callBack
    )
}
