// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           37
// Async Callback:                       1
// Total number of exported functions:  39

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    elven_nft_minter
    (
        init => init
        upgrade => upgrade
        getNftTokenId => nft_token_id
        getCollectionTokenName => collection_token_name
        getNftTokenName => nft_token_name
        getNftPrice => selling_price
        getProvenanceHash => provenance_hash
        getTokensLimitPerAddressTotal => tokens_limit_per_address_total
        getMintedPerAddressTotal => minted_per_address_total
        getTokensLimitPerAddressPerDrop => tokens_limit_per_address_per_drop
        isAllowlistEnabled => is_allowlist_enabled
        isDropActive => is_drop_active
        getTotalSupply => amount_of_tokens_total
        isMintingPaused => paused
        getTotalSupplyOfCurrentDrop => amount_of_tokens_per_drop
        issueToken => issue_token
        setLocalRoles => set_local_roles
        pauseMinting => pause_minting
        startMinting => start_minting
        setDrop => set_drop
        unsetDrop => unset_drop
        setNewPrice => set_new_price
        changeBaseCids => change_base_cids
        setNewTokensLimitPerAddress => set_new_tokens_limit_per_address
        giveaway => giveaway
        claimScFunds => claim_sc_funds
        enableAllowlist => enable_allowlist
        disableAllowlist => disable_allowlist
        populateAllowlist => populate_allowlist
        clearAllowlist => clear_allowlist
        removeAllowlistAddress => remove_allowlist_address
        mint => mint
        shuffle => shuffle
        getDropTokensLeft => drop_tokens_left
        getTotalTokensLeft => total_tokens_left
        getMintedPerAddressPerDrop => get_minted_per_address_per_drop
        getAllowlistAddressCheck => allowlist_address_check
        getAllowlistSize => allowlist_size
    )
}

multiversx_sc_wasm_adapter::async_callback! { elven_nft_minter }
